# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.srcs/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0.xci
# IP: The module: 'PWM_BLOCK_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.gen/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_BLOCK_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.gen/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_BLOCK_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.gen/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_BLOCK_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.srcs/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0.xci
# IP: The module: 'PWM_BLOCK_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.gen/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_BLOCK_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.gen/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_BLOCK_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.gen/sources_1/bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_BLOCK_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
