# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/Cmod-A7-Master.xdc

# Block Designs: bd/PWM_BLOCK/PWM_BLOCK.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_BLOCK || ORIG_REF_NAME==PWM_BLOCK} -quiet] -quiet

# IP: bd/PWM_BLOCK/ip/PWM_BLOCK_clk_wiz_0_0/PWM_BLOCK_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_BLOCK_clk_wiz_0_0 || ORIG_REF_NAME==PWM_BLOCK_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PWM_BLOCK/ip/PWM_BLOCK_BlockRAM_0_0/PWM_BLOCK_BlockRAM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_BLOCK_BlockRAM_0_0 || ORIG_REF_NAME==PWM_BLOCK_BlockRAM_0_0} -quiet] -quiet

# IP: bd/PWM_BLOCK/ip/PWM_BLOCK_BlockRamDummy_0_0/PWM_BLOCK_BlockRamDummy_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_BLOCK_BlockRamDummy_0_0 || ORIG_REF_NAME==PWM_BLOCK_BlockRamDummy_0_0} -quiet] -quiet

# IP: bd/PWM_BLOCK/ip/PWM_BLOCK_PWM_TEST_0_0/PWM_BLOCK_PWM_TEST_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_BLOCK_PWM_TEST_0_0 || ORIG_REF_NAME==PWM_BLOCK_PWM_TEST_0_0} -quiet] -quiet

# IP: bd/PWM_BLOCK/ip/PWM_BLOCK_I2CMaster_0_0/PWM_BLOCK_I2CMaster_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_BLOCK_I2CMaster_0_0 || ORIG_REF_NAME==PWM_BLOCK_I2CMaster_0_0} -quiet] -quiet

# XDC: c:/Users/jakob/PWM_MOD_TEST/PWM_MOD_TEST.gen/sources_1/bd/PWM_BLOCK/PWM_BLOCK_ooc.xdc
